#!/usr/bin/env python
"Autonomously move Neato forward 1m"

import rospy

from geometry_msgs.msg import Twist, Vector3
from nav_msgs.msg import Odometry

class Odom1(object):
	def __init__(self,target_distance):

		rospy.init_node('Odom1')
		self.pub = rospy.Publisher("/cmd_vel",Twist, queue_size = 10)
		self.sub = rospy.Subscriber ("/odom", Odometry, process_odom)

	def process_odom(self,msg):
		self.x = msg.pose.pose.position.x
		self.velocity = 1.0*()

	def run(self):
		r = rospy.Rate(5)
		while not rospy.is_shutdown():
			self.pub.publish(Twist(linear = Vector3(x = self.velocity))
			r.sleep()

if __name__=='__main__':
	node = Odom1(1)  #distance in meters
	node.run()